### ISSUE TITLE
Might want to remove your private keys.

### ISSUE THREAD

**Issue by Bilg21** [gibranlp/QARSlp#11]
[dotfiles](https://github.com/gibranlp/QARSlp/tree/develop/dotfiles)/[.config](https://github.com/gibranlp/QARSlp/tree/develop/dotfiles/.config)/[task](https://github.com/gibranlp/QARSlp/tree/develop/dotfiles/.config/task)

Awesome work @gibranlp . But you might want to remove your keys from public :eye: :eye:

**Comment by gibranlp** [comment]
Right, will do, I was just using them as testing for now.

Thanks! I appreciate.
