### ISSUE TITLE
[Request] sddm-git

### ISSUE THREAD

**Issue by Sachin-Bhat** [gibranlp/QARSlp#16]
Hey @gibranlp your config looks amazing!
This is kind of related to #15. I have other wayland compositors running and they don't work well with lightDM so I was wondering if you could integrate sddm-git which has support for wayland into your scripts.

**Comment by gibranlp** [comment]
Yeah I can try, actually in the beginning was trying to use sddm as the default login manager, can't remember why i changed to Lightdm, it might take me some time though, right now I am focusing on trying to make this an Arch based distro, but will look into it.
